version: '3.4'
services:
  node-starter-server:
    container_name: node-server
    build: .
    ports:
      - 3000:4000
  mongodb:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - node-starter-data:/data/db
volumes:
  node-starter-data:
